### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by nelsam** [Cryptolens/cryptolens-golang#1]
The cryptolens library has no license applied to it.  This means that we get in to problems with legal if we import it into our software.

Please add a license (BSD, MIT, apache...) to cryptolens-golang so that we can legally import it into our software.

See [the licensing policy at pkg.go.dev](https://pkg.go.dev/license-policy).

**Comment by artemlos** [comment]
@nelsam Hi! Thanks for the feedback.

I have added the missing license file (MIT license).
