### ISSUE TITLE
Missing HasFeature function.

### ISSUE THREAD

**Issue by LabGuy94** [Cryptolens/cryptolens-golang#2]
In the cryptolens python version, you can find a HasFeature function which returns if the user owns that feature in the "Feature Template". I'm not able to find this function in the golang version.

**Comment by artemlos** [comment]
@LabGuy94 thanks for the feedback! It's now on our backlog to add this method to Golang.

If you need this feature urgently, please reach out to us at support@cryptolens.io or by sending a message through the chat box.
