### ISSUE TITLE
Not working with V3 ?

### ISSUE THREAD

**Issue by d4op** [Cryptolens/cryptolens-golang#3]
the example is not working for me with the example code.
can you please update ?

**Comment by svedi** [comment]
Hi, we tried responding to you on Intercom, I'm not sure if you got the message.

It's unclear what you mean by the example not working in this case. Is the example not working as is, or when you attempt to use it for your account. When using it for your account you need to update the `token` and `publicKey` variables with the values for your account. You can find/generate these values from the menu on the top-right on the website.

I see that the error messages are a bit unclear in the golang library, and we are working on improving them.

**Comment by d4op** [comment]
i used the rsa and token of my account with the example code it doesnt work.

**Comment by svedi** [comment]
Does the example work when you do not change any of the values? If that is the case, can you check that you added the Activate permission to your access token, and that you did not lock the access token to any particular product/key etc.

**Comment by d4op** [comment]
i only activated activate key feature on the product id i created

**Comment by d4op** [comment]
Name | Permission | Product | Key | Feature |  
dL2 | * Get Key; * Activate; * Deactivate; | Any | Any | Any

./example_activate
License key activation failed!

**Comment by svedi** [comment]
Can you confirm that the example is working if you do not change any of the values?

**Comment by svedi** [comment]
We have made a guide for how to troubleshoot API errors here: https://help.cryptolens.io/faq/index#troubleshooting-api-errors

Could you check if the issue exists even when using curl or if it is related to the go library?

**Comment by d4op** [comment]
when i use the troubleshooting get curl with my keys and tokens.

{"result":1,"message":"No active subscription found. Please contact support."}#                                                                          

ah its because of the subscription which is inactive ?!

**Comment by artemlos** [comment]
@d4op 

That's correct. An active subscription is necessary to use Cryptolens.
